### ISSUE TITLE
Open pdf file at page ?

### ISSUE THREAD

**Issue by abrasat** [rohitvipin/PdfViewerSample#1]
Is it possible with the PdfViewer to open a pdf file to a certain page or chapter ? If yes, please post code sample how to do it.

**Comment by rohitvipin** [comment]
You can look at PdfJS to see how to do it. Yes it's totally possible. You can either pass in a page number parameter or modify the load method.

**Comment by abrasat** [comment]
Ok, thanks, I'll take a look.
Is it possible to open also pdf files included as embedded resources into the Xamarin.Forms application ?
Is there any sample available for local pdf files, without the need of accessing any rest apis to get the files from Internet ?

**Comment by rohitvipin** [comment]
Yes, the sample for the same could be found in the Xamarin website mentioned in the blog post.

**Comment by abrasat** [comment]
I found the pdf.js option (#page=xx)

https://github.com/mozilla/pdf.js/wiki/Viewer-options

but cannot figure out how to use it in the PdfViewerSample

**Comment by rohitvipin** [comment]
You can update the viewer.html file or pass as query string. The code is
available in the custom render.
