### ISSUE TITLE
PdfViewer for UWP

### ISSUE THREAD

**Issue by abrasat** [rohitvipin/PdfViewerSample#2]
It looks that the PdfViewer is not working for UWP. No pdf file content is displayed for UWP, it only works for the Android application (cannot test iOS).

**Comment by rohitvipin** [comment]
I have not implemented it for UWP, I had only requirements for Android and iOS, feel free to create a PR if you can do it for UWP

**Comment by abrasat** [comment]
The problem is that PCLStorage was used for reading/writing *.pdf files on the device, and I dont think it can be used with UWP.

**Comment by rohitvipin** [comment]
It's supposrted. If not you can always write a service and use it via DI for UWP
