### ISSUE TITLE
PdfViewer - pass decoded base64 data as an array to pdf.js

### ISSUE THREAD

**Issue by abrasat** [rohitvipin/PdfViewerSample#3]
Pdf.js supports also pdf content as decoded base64 data as an array.
Can the PdfViewerSample use this pdf.js functionality ?

**Comment by rohitvipin** [comment]
No it doesn't now. It currently support direct files only.
You can tweak and make that working.
Add a parameter base64 like Uri and then pass that instead of file path.

**Comment by abrasat** [comment]
And what should be used in this case instead of 

 Control.LoadUrl($"file:///android_asset/pdfjs/web/viewer.html?file=file://{uri}");
?

**Comment by rohitvipin** [comment]
That's how to load a file, you have to check how to load base64. I don't
have any requirement to update or look into other options. You will have to
look PdfJs for options. Or you can look at Syncfusion or any other paid
components.
